export const FETCH_WEDDINGS = 'FETCH_WEDDINGS';
export const ADD_WEDDING = 'ADD_WEDDING';
export const UPDATE_WEDDING = 'UPDATE_WEDDING';
export const DELETE_WEDDING = 'DELETE_WEDDING';
export const EDIT_WEDDING = 'EDIT_WEDDING';

export const FETCH_FOODS = 'FETCH_FOODS';
export const ADD_FOOD = 'ADD_FOOD';
export const UPDATE_FOOD = 'UPDATE_FOOD';
export const DELETE_FOOD = 'DELETE_FOOD';
export const EDIT_FOOD = 'EDIT_FOOD';

export const FETCH_SERVICES = 'FETCH_SERVICES';
export const ADD_SERVICE = 'ADD_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';

export const FETCH_SHIFTS = 'FETCH_SHIFTS';
export const ADD_SHIFT = 'ADD_SHIFT';
export const UPDATE_SHIFT = 'UPDATE_SHIFT';
export const DELETE_SHIFT = 'DELETE_SHIFT';
export const EDIT_SHIFT = 'EDIT_SHIFT';

export const FETCH_LOBBIES = 'FETCH_LOBBIES';
export const ADD_LOBBY = 'ADD_LOBBY';
export const UPDATE_LOBBY = 'UPDATE_LOBBY';
export const DELETE_LOBBY = 'DELETE_LOBBY';
export const EDIT_LOBBY = 'EDIT_LOBBY';

export const FETCH_TABLES = 'FETCH_TABLES';
export const ADD_TABLE = 'ADD_TABLE';
export const UPDATE_TABLE = 'UPDATE_TABLE';
export const DELETE_TABLE = 'DELETE_TABLE';
export const EDIT_TABLE = 'EDIT_TABLE';

export const FETCH_TABLECATEGORIES = 'FETCH_TABLECATEGORIES';
export const ADD_TABLECATEGORY = 'ADD_TABLECATEGORY';
export const UPDATE_TABLECATEGORY = 'UPDATE_TABLECATEGORY';
export const DELETE_TABLECATEGORY = 'DELETE_TABLECATEGORY';
export const EDIT_TABLECATEGORY = 'EDIT_TABLECATEGORY';

export const FETCH_TABLEFOODS = 'FETCH_TABLEFOODS';
export const ADD_TABLEFOOD = 'ADD_TABLEFOOD';
export const UPDATE_TABLEFOOD = 'UPDATE_TABLEFOOD';
export const DELETE_TABLEFOOD = 'DELETE_TABLEFOOD';
export const EDIT_TABLEFOOD = 'EDIT_TABLEFOOD';

export const FETCH_WEDDINGSERVICES = 'FETCH_WEDDINGSERVICES';
export const ADD_WEDDINGSERVICE = 'ADD_WEDDINGSERVICE';
export const UPDATE_WEDDINGSERVICE = 'UPDATE_WEDDINGSERVICE';
export const DELETE_WEDDINGSERVICE = 'DELETE_WEDDINGSERVICE';
export const EDIT_WEDDINGSERVICE = 'EDIT_WEDDINGSERVICE';

export const FETCH_NOTPAIDBILLS = 'FETCH_NOTPAIDBILLS';
export const ADD_NOTPAIDBILL = 'ADD_NOTPAIDBILL';
export const UPDATE_NOTPAIDBILL = 'UPDATE_NOTPAIDBILL';
export const DELETE_NOTPAIDBILL = 'DELETE_NOTPAIDBILL';
export const EDIT_NOTPAIDBILL = 'EDIT_NOTPAIDBILL';

export const FETCH_PAIDBILLS = 'FETCH_PAIDBILLS';
export const ADD_PAIDBILL = 'ADD_PAIDBILL';
export const UPDATE_PAIDBILL = 'UPDATE_PAIDBILL';
export const DELETE_PAIDBILL = 'DELETE_PAIDBILL';
export const EDIT_PAIDBILL = 'EDIT_PAIDBILL';

export const FETCH_USERS = 'FETCH_USERS';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';